services:
  postgres:
    container_name: airline_db
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: airline_db
      POSTGRES_USER: airline_user
      POSTGRES_PASSWORD: airline_pw
    ports:
      - 5432:5432