spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airline_db
    username: airline_user
    password: airline_pw
  flyway:
    locations: classpath:/db/tables, classpath:/db/data

server:
  error:
    include-message: always


